### ISSUE TITLE
Usage of ISO codes 

### ISSUE THREAD

**Issue by mlisovyi** [MouadBH/coronapy-cli#1]
Great tool for python users! Thanks for introducing it.

The country endpoint of  `NovelCOVID/API` supports usage of ISO codes for contries, e.g. DE/DEU for Germany. However, their `historical` endpoint does not support ISO codes as inputs :(. For this cli tool this means, that the country info is extracted also with the short ISO code instead of the full name, but the histogram works only with the full name . The histogramming part should catch such problem at the very least or try converting ISO codes into full name at  best.

Example:
```bash
$ coronapy country de -h -t cases
...
Civid-19 'cases' for last 20 day in de.
Traceback (most recent call last):
  File "xxx/anaconda3/bin/coronapy", line 10, in <module>
    sys.exit(cli())
  File "xxx/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "xxx/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "xxx/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "xxx/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "xxx/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "xxx/anaconda3/lib/python3.6/site-packages/coronapy/cli.py", line 114, in country
    tg.chart(colors=[91, 94], data=hist_data, args=args, labels=labels_hist)
  File "xxx/anaconda3/lib/python3.6/site-packages/termgraph/termgraph.py", line 353, in chart
    len_categories = len(data[0])
IndexError: list index out of range
```

Used **Corona-cli v1.2.3**

**Comment by MouadBH** [comment]
Thank for your contribution❤ , branch merged.
